//! Generated by `scripts/generate_contract_manifest.py`; do not edit by hand.
//!
//! These are implementation/package identity pins, not additional normative
//! sources (which would create a self-referential contract digest).

/// This crate's installable package version.
pub const PACKAGE_VERSION: &str = env!("CARGO_PKG_VERSION");

/// SHA-256 of the complete normative source set in `contract/manifest.v1.json`.
pub const NORMATIVE_CONTRACT_DIGEST: &str =
    "9cae331742d01e9b164e029aa06c644e6b1886176d0816a6ef883af138355c90";

/// Build/source identity supplied by the immutable release builder. The checked-in
/// RC default is deliberately non-certifying and must not be presented as a commit.
/// A raw `NCP_BUILD_IDENTITY` compiler input is not validation or provenance; only
/// the fail-closed release builder validates and binds an exact source revision.
pub const BUILD_IDENTITY: &str = match option_env!("NCP_BUILD_IDENTITY") {
    Some(identity) => identity,
    None => "unreleased-worktree",
};

#[cfg(test)]
mod tests {
    #[test]
    fn build_identity_matches_release_builder_expectation() {
        let expected = option_env!("NCP_EXPECTED_BUILD_IDENTITY").unwrap_or("unreleased-worktree");
        assert_eq!(super::BUILD_IDENTITY, expected);
    }
}
