// Generated by scripts/generate_contract_manifest.py; do not edit by hand.
// Package/build identity is informative and deliberately outside the normative digest.
export const NCP_PACKAGE_VERSION = '1.0.0-rc.1'
export const NCP_NORMATIVE_CONTRACT_DIGEST = '9cae331742d01e9b164e029aa06c644e6b1886176d0816a6ef883af138355c90'
export const NCP_BUILD_IDENTITY = 'unreleased-worktree'
