// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ChannelKind } from "./ChannelKind";
import type { ChannelRequirement } from "./ChannelRequirement";

/**
 * Declares a named channel a controller produces or consumes.
 */
export type ChannelSpec = { name: string, kind: ChannelKind, unit: string | null, size: bigint | null, requirement: ChannelRequirement, description: string | null, };
