// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AuthorityLease } from "./AuthorityLease";
import type { ChannelValue } from "./ChannelValue";
import type { Mode } from "./Mode";
import type { SessionRef } from "./SessionRef";
import type { StreamPosition } from "./StreamPosition";

/**
 * Controller → plant: the proposed actuation, with `mode`/`ttl_ms` safety
 * metadata.
 *
 * `stream`/`t` belong to the command publisher and advance independently of the
 * sensor stream. A closed-loop command carries the driving sensor position/time
 * in `source`/`source_t`; consumers correlate on `source`, never by equating the
 * two publishers' `stream.seq` or clocks. `ActionBuffer` and
 * `CommandWatchdog` apply replay/freshness discipline to the command's own stream.
 */
export type CommandFrame = { ncp_version: string, kind: string, t: number, frame_id: string, mode: Mode, ttl_ms: number, channels: { [key in string]: ChannelValue },
/**
 * Packetized predictive control: future setpoints. `channels` is tick 0;
 * `horizon[i]` applies at tick i+1, spaced `horizon_dt_ms` apart. The
 * actuator replays these through dropouts (see `ActionBuffer`), bounded by
 * `ttl_ms`. Empty = legacy single-step command. Backward compatible: a
 * consumer that ignores `horizon` still reads `channels` (tick 0).
 */
horizon: Array<{ [key in string]: ChannelValue }>, horizon_dt_ms: number | null,
/**
 * Wire 0.8: this command stream's own incarnation + position — the sequence
 * `LinkMonitor`/`ActionBuffer` read for loss/dedup/supersession.
 */
stream: StreamPosition,
/**
 * The driving `SensorFrame.stream` (correlation only; never loss accounting).
 * Present for a closed-loop Active command; omitted for negotiated open-loop.
 */
source: StreamPosition | null,
/**
 * The driving `SensorFrame.t`, for source-age checks; `0.0` = unset.
 */
source_t: number,
/**
 * The live session incarnation this command stream belongs to.
 */
session: SessionRef,
/**
 * Logical session id (transport-neutral); MUST equal the routing key's session.
 */
session_id: string,
/**
 * Required for Active/HOLD authority-bearing commands. Authenticated ESTOP
 * may omit it so a stale lease cannot suppress the fail-safe latch.
 */
authority: AuthorityLease | null, };
