// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Visible attribution for a deliberately translated legacy payload. Native
 * peers omit it; its presence never upgrades the legacy source's security or
 * scientific/safety evidence.
 */
export type GatewayAttribution = { gateway_id: string, source_wire: string, };
