// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Plane } from "./Plane";
import type { PrincipalRole } from "./PrincipalRole";

/**
 * Payload claim that an authenticated transport adapter binds to its verified
 * peer identity. The claim never authenticates itself.
 */
export type IdentityClaim = { principal_id: string, entity_id: string, role: PrincipalRole, plane: Plane, };
