// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EntityBinding } from "./EntityBinding";
import type { GatewayAttribution } from "./GatewayAttribution";
import type { IdentityClaim } from "./IdentityClaim";
import type { NetworkRef } from "./NetworkRef";
import type { RecordSpec } from "./RecordSpec";
import type { SimConfig } from "./SimConfig";
import type { StimulusSpec } from "./StimulusSpec";

/**
 * Request a simulation: declare what to record and what to stimulate.
 */
export type OpenSession = { ncp_version: string, kind: string, session_id: string, network: NetworkRef, record: RecordSpec, stimulus: StimulusSpec, sim: SimConfig, bindings: Array<EntityBinding>,
/**
 * Caller's [`CONTRACT_HASH`], carried in the handshake as an **advisory**
 * identity signal (see [`ContractStatus`]): a mismatch is logged, not rejected —
 * `ncp_version` is the hard compatibility gate. Defaults to our own hash so
 * every session advertises it; `None` (serialized `null`) = not advertised.
 */
contract_hash: string | null,
/**
 * Authenticated caller claim; the transport adapter binds it to the peer
 * certificate before opening any session state.
 */
identity: IdentityClaim, security_profile: string, security_state_digest: string,
/**
 * Explicit opt-in to a labelled 0.8→1.0 gateway. `false` is native-only.
 */
gateway_permitted: boolean,
/**
 * Present only when this payload was emitted by a terminating gateway.
 */
gateway: GatewayAttribution | null, };
