// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Transport plane named by an authenticated principal claim. Security enums are
 * closed: an unknown plane never inherits authority from a known one.
 */
export type Plane = "unknown" | "control" | "perception" | "action" | "observation";
