// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ChannelValue } from "./ChannelValue";
import type { SessionRef } from "./SessionRef";
import type { StreamPosition } from "./StreamPosition";

/**
 * Plant → controller: the latest sensed state. Its own `stream`/`t` identify the
 * sensor publication; a derived command correlates it through `source`/`source_t`
 * without copying those values into the command publisher's own identity.
 * Publishers stamp `stream.seq` starting at `1`, strictly increasing within a
 * canonical `stream.epoch`. `stream.seq = 0` is unstamped and rejected.
 */
export type SensorFrame = { ncp_version: string, kind: string, t: number, frame_id: string, channels: { [key in string]: ChannelValue },
/**
 * Wire 0.8: this sensor stream's own incarnation + position — the ONLY sequence
 * loss/`LinkMonitor`/`ActionBuffer` accounting reads. The origin: no `source`;
 * downstream `command`/`observation` `source` copies THIS `stream` position.
 */
stream: StreamPosition,
/**
 * The live session incarnation this stream belongs to (server-issued generation).
 */
session: SessionRef,
/**
 * Logical session id (transport-neutral); MUST equal the routing key's session
 * segment. Carried in-payload so a non-keyed transport can interpret the frame.
 */
session_id: string, };
