// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ChannelValue } from "./ChannelValue";

/**
 * Plant → controller: the latest sensed state. Carries `seq`/`t` so a command
 * can be stamped with the sensor it was computed from (the correspondence the
 * split perception/action planes must preserve — join on `seq`, not arrival).
 *
 * Wire 0.6 (normative): publishers MUST stamp `seq` starting at `1`, strictly
 * increasing per stream. `seq = 0` is "unstamped" — receivers drop it (it is
 * also the serde default, so a default-constructed frame is not wire-legal
 * until stamped). `t` is producer-local monotonic seconds and is never compared
 * across peers.
 */
export type SensorFrame = { ncp_version: string, kind: string, seq: bigint, t: number, frame_id: string, channels: { [key in string]: ChannelValue }, };
