// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AuthorityLease } from "./AuthorityLease";
import type { OperationContext } from "./OperationContext";
import type { SessionRef } from "./SessionRef";
import type { StimulusFrame } from "./StimulusFrame";

/**
 * Advance one chunk; optional stimulus; returns an `ObservationFrame`.
 */
export type StepRequest = { ncp_version: string, kind: string, session_id: string, advance_ms: number | null, stimulus: StimulusFrame | null,
/**
 * (0.8) REQUIRED: targets an open incarnation; `(session_id, generation)` live pair.
 */
session: SessionRef, operation: OperationContext, authority: AuthorityLease, };
